name: Test Shared Workflow

on:
  push:
    branches:
      - main

jobs:
  test-shared-workflow:
    uses: yggdrasilcorp/tp-templates/.github/workflows/template.yml@main
    with:
      java-v: '23'
      web_name: 'webgoat'
      network-name: 'webgoat-net'
      url: 'http://webgoat:8080/WebGoat'
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}