name: Call Shared Workflow

on:
  push:
    branches:
      - main

jobs:
  call-shared-workflow:
    uses: yggdrasilcorp/tp-templates/.github/workflows/template.yml@main
    with:
      java-v: '23'
      web_name: 'webgoat'
      network-name: 'webgoat-net'
      url: 'http://webgoat:8080/WebGoat'
